server:
  port: 8085
  error:
    path: /error
  servlet:
    encoding:
      force-response: true

spring:
  security:
    user:
      name: user
      password: 1234
  profiles:
    active: local
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  mvc:
    servlet:
      path: /
    static-path-pattern: /static/**
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/office
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000



logging:
  config: classpath:logback.xml
  level:
    org:
      springframework: info