name: Auto-Commit
on:
  push:
    branches:
      - master
      - feature/*
jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Node.js 20을 지원하는 최신 버전 사용
      - name: Configure git
        run: |
          git config user.name "leeho7029"
          git config user.email "80402477+leeho7029@users.noreply.github.com."
      - name: Make changes
        run: |
          # 여기에 변경 사항을 적용하는 스크립트를 작성합니다
          echo "Some changes" > file.txt
      - name: Commit changes
        run: |
          git add .
          git commit -m "Auto commit: ${GITHUB_SHA}"
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin ${{ github.ref }}