name: Office-Actions
on:
  push:
    branches:
      - master
      - feature/*
  pull_request:
    branches:
      - master
      - feature/*
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Auto PR: ${GITHUB_SHA}"
          branch: ${{ github.ref }}  # 푸시된 브랜치를 대상으로 PR 생성
          title: "자동PR GithubAction"
          body: "자동으로 PR됨"
      - name: Save PR URL
        id: pr_url
        run: echo "PR URL - ${{ steps.create-pull-request.outputs.pull-request-url }}"